services:
  - type: web
    name: eia-football-league
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
